import IndexLayout from '@/layout';
import { Manrope } from '@next/font/google';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import { Product } from '../typings';
import { fetchProducts } from '../utils/fetchProducts';
import Categories from './components/Categories';
import Footer from './components/Footer';
import Hero from './components/Hero';
import Navbar from './components/Navbar';
import ProductShowcase from './components/ProductShowcase';

const manrope = Manrope({
  weight: ['200', '300', '400', '500', '700', '800'],
  style: ['normal'],
  subsets: ['latin'],
});

type Props = {
  products: Product[];
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style jsx global>{`
          html {
            font-family: ${manrope.style.fontFamily};
          }
        `}</style>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <IndexLayout>
        <Hero />
        <Categories />
        <ProductShowcase />
      </IndexLayout>
      <Footer />
    </>
  );
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const products: Product[] = await fetchProducts();

  return {
    props: {
      products,
    },
    revalidate: 10,
  };
};
