import { Manrope } from '@next/font/google';
import Head from 'next/head';
import About from './components/About';
import Categories from './components/Categories';
import Footer from './components/Footer';
import Navbar from './components/Navbar';

const manrope = Manrope({
  weight: ['200', '300', '400', '500', '700', '800'],
  style: ['normal'],
  subsets: ['latin'],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style jsx global>{`
          html {
            font-family: ${manrope.style.fontFamily};
          }
        `}</style>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Categories />
        <About />
      </main>
      <Footer />
    </>
  );
}
